// // 侧边栏数据
export const siderData = [
    {linkName:'html'},
    {linkName:'css'},
    {linkName:'javascript'},
    {linkName:'tool'},
    {linkName:'Js template'},
    {linkName:'nodeJs'},
    {linkName:'blog'},
    {linkName:'community'},
    {linkName:'database'}
]
export const mainData = [
    {
        id:'modal-1',
        linkName:'html',
        itemWrap:[
            {
                imgUrl:require('@/assets/img/foundation.png'),
                itemName:'foundation',
                linkWrap:[
                    {
                        linkUrl:'http://foundation.zurb.com/',
                        linkType:'中'
                    },
                    {   
                        linkUrl:'http://getbootstrap.com/',
                        linkType:'英'
                    }
                ]
            },
            {
                imgUrl:require('@/assets/img/bootstrap.png'),
                itemName:'bootstrap',
                linkWrap:[
                    {
                        linkUrl:'http://www.bootcss.com/',
                        linkType:'中'
                    },
                    {   
                        linkUrl:'http://getbootstrap.com/',
                        linkType:'英'
                    }
                ]
            },
            {
                imgUrl:require('@/assets/img/default.png'),
                itemName:'metronic4.7.1',
                linkWrap:[
                    {   
                        linkUrl:'http://i0.mallcoo.net/mc/metronic4.7.1/demo/admin_1/form_controls.html',
                        linkType:'英'
                    }
                ]
            }
        ]
    },
    {
        id:'modal-2',
        linkName:'css',
        itemWrap:[
            {
                imgUrl:require('@/assets/img/sass.png'),
                itemName:'sass',
                linkWrap:[
                    {
                        linkUrl:'https://www.sass.hk/',
                        linkType:'中'
                    },
                    {   
                        linkUrl:'http://sass-lang.com/',
                        linkType:'英'
                    }
                ]
            },
            {
                imgUrl:require('@/assets/img/less.png'),
                itemName:'less',
                linkWrap:[
                    {
                        linkUrl:'http://less.bootcss.com/',
                        linkType:'中'
                    },
                    {   
                        linkUrl:'http://lesscss.org/',
                        linkType:'英'
                    }
                ]
            },
            {
                imgUrl:require('@/assets/img/stylus.png'),
                itemName:'stylus',
                linkWrap:[
                    {   
                        linkUrl:'http://stylus-lang.com/',
                        linkType:'英'
                    }
                ]
            }
        ]
    },
    {
        id:'modal-3',
        linkName:'javascript',
        itemWrap:[
            {
                imgUrl:require('@/assets/img/plain.png'),
                itemName:'plainjs',
                linkWrap:[
                    {   
                        linkUrl:'https://plainjs.com/javascript/',
                        linkType:'英'
                    }
                ]
            },
            {
                imgUrl:require('@/assets/img/default.png'),
                itemName:'ES6',
                linkWrap:[
                    {
                        linkUrl:'http://es6.ruanyifeng.com/',
                        linkType:'中'
                    },
                    {
                        linkUrl:'http://www.infoq.com/cn/es6-in-depth/',
                        linkType:'中'
                    },
                    {   
                        linkUrl:'http://www.ecma-international.org/ecma-262/6.0/',
                        linkType:'英'
                    }
                ]
            },
            {
                imgUrl:require('@/assets/img/jquery.png'),
                itemName:'Jquery',
                linkWrap:[
                    {
                        linkUrl:'http://www.jquery123.com/',
                        linkType:'中'
                    },
                    {
                        linkUrl:'http://jquery.com/',
                        linkType:'英'
                    },
                    {   
                        linkUrl:'http://jquery.cuishifeng.cn/',
                        linkType:'API'
                    }
                ]
            },
            {
                imgUrl:require('@/assets/img/vue.png'),
                itemName:'vue',
                linkWrap:[
                    {
                        linkUrl:'https://cn.vuejs.org/',
                        linkType:'中'
                    }
                ]
            },
            {
                imgUrl:require('@/assets/img/angular.png'),
                itemName:'Angularjs',
                linkWrap:[
                    {
                        linkUrl:'http://www.angularjs.net.cn/',
                        linkType:'中'
                    },
                    {   
                        linkUrl:'https://angularjs.org/',
                        linkType:'英'
                    }
                ]
            },
            {
                imgUrl:require('@/assets/img/react.png'),
                itemName:'React',
                linkWrap:[
                    {
                        linkUrl:'http://nav.react-china.org/',
                        linkType:'中'
                    },
                    {   
                        linkUrl:'https://facebook.github.io/react/',
                        linkType:'英'
                    }
                ]
            },
            {
                imgUrl:require('@/assets/img/react.png'),
                itemName:'React Native',
                linkWrap:[
                    {
                        linkUrl:'http://reactnative.cn/',
                        linkType:'中'
                    },
                    {   
                        linkUrl:'https://facebook.github.io/react-native/',
                        linkType:'英'
                    }
                ]
            },
        ]
    },
    {
        id:'modal-4',
        linkName:'tool',
        itemWrap:[
            {
                imgUrl:require('@/assets/img/gulp.png'),
                itemName:'gulp',
                linkWrap:[
                    {
                        linkUrl:'http://www.gulpjs.com.cn/',
                        linkType:'中'
                    },
                    {   
                        linkUrl:'https://gulpjs.com/',
                        linkType:'英'
                    }
                ]
            },
            {
                imgUrl:require('@/assets/img/webpack.png'),
                itemName:'webpack',
                linkWrap:[
                    {
                        linkUrl:'http://www.css88.com/doc/webpack2/guides/development/',
                        linkType:'中'
                    },
                    {   
                        linkUrl:'https://webpack.js.org/',
                        linkType:'英'
                    },
                ]
            },
            {
                imgUrl:require('@/assets/img/grunt.png'),
                itemName:'grunt',
                linkWrap:[
                    {   
                        linkUrl:'https://gruntjs.com/',
                        linkType:'英'
                    }
                ]
            },
            {
                imgUrl:require('@/assets/img/cordova.png'),
                itemName:'cordova',
                linkWrap:[
                    {   
                        linkUrl:'http://cordova.axuer.com/',
                        linkType:'中'
                    },
                    {   
                        linkUrl:'http://cordova.apache.org/',
                        linkType:'英'
                    }
                ]
            }
        ]
    },
    {
        id:'modal-5',
        linkName:'Js template',
        itemWrap:[
            {
                imgUrl:require('@/assets/img/ejs.png'),
                itemName:'ejs',
                linkWrap:[
                    {   
                        linkUrl:'http://www.ejs.co/',
                        linkType:'英'
                    }
                ]
            },
            {
                imgUrl:require('@/assets/img/art-template.png'),
                itemName:'art-template',
                linkWrap:[
                    {
                        linkUrl:'https://aui.github.io/art-template/',
                        linkType:'中'
                    }
                ]
            },
            {
                imgUrl:require('@/assets/img/segmentfault.png'),
                itemName:'other',
                linkWrap:[
                    {
                        linkUrl:'https://segmentfault.com/a/1190000000502743',
                        linkType:'中'
                    }
                ]
            }
        ]
    },
    {
        id:'modal-6',
        linkName:'nodeJs',
        itemWrap:[
            {
                imgUrl:require('@/assets/img/koa.png'),
                itemName:'koa',
                linkWrap:[
                    {
                        linkUrl:'http://koa.bootcss.com/',
                        linkType:'中'
                    },
                    {   
                        linkUrl:'http://koajs.com/',
                        linkType:'英'
                    }
                ]
            },
            {
                imgUrl:require('@/assets/img/express.png'),
                itemName:'express',
                linkWrap:[
                    {
                        linkUrl:'http://www.expressjs.com.cn/',
                        linkType:'中'
                    },
                    {   
                        linkUrl:'http://expressjs.com/',
                        linkType:'英'
                    }
                ]
            }
        ]
    },
    {
        id:'modal-7',
        linkName:'blog',
        itemWrap:[
            {
                imgUrl:require('@/assets/img/default.png'),
                itemName:'廖雪峰',
                linkWrap:[
                    {
                        linkUrl:'https://www.liaoxuefeng.com/',
                        linkType:'中'
                    }
                ]
            },
            {
                imgUrl:require('@/assets/img/default.png'),
                itemName:'阮一峰',
                linkWrap:[
                    {
                        linkUrl:'http://www.ruanyifeng.com/blog/',
                        linkType:'中'
                    }
                ]
            },
            {
                imgUrl:require('@/assets/img/cnblogs.png'),
                itemName:'汤姆大叔',
                linkWrap:[
                    {
                        linkUrl:'http://www.cnblogs.com/TomXu/',
                        linkType:'中'
                    }
                ]
            },
            {
                imgUrl:require('@/assets/img/cnblogs.png'),
                itemName:'豪情',
                linkWrap:[
                    {
                        linkUrl:'http://jikey.cnblogs.com/',
                        linkType:'中'
                    }
                ]
            },
            {
                imgUrl:require('@/assets/img/zxx.png'),
                itemName:'张鑫旭',
                linkWrap:[
                    {
                        linkUrl:'http://www.zhangxinxu.com/',
                        linkType:'中'
                    }
                ]
            }
        ]
    },
    {
        id:'modal-8',
        linkName:'community',
        itemWrap:[
            {
                imgUrl:require('@/assets/img/stackoverflow.png'),
                itemName:'stackoverflow',
                linkWrap:[
                    {   
                        linkUrl:'https://stackoverflow.com/',
                        linkType:'英'
                    }
                ]
            },
            {
                imgUrl:require('@/assets/img/github.png'),
                itemName:'github',
                linkWrap:[
                    {   
                        linkUrl:'https://github.com/',
                        linkType:'英'
                    }
                ]
            },
            {
                imgUrl:require('@/assets/img/juejin.png'),
                itemName:'掘金',
                linkWrap:[
                    {
                        linkUrl:'https://juejin.im/',
                        linkType:'中'
                    }
                ]
            },
            {
                imgUrl:require('@/assets/img/oschina.png'),
                itemName:'开源中国',
                linkWrap:[
                    {
                        linkUrl:'https://www.oschina.net/',
                        linkType:'中'
                    }
                ]
            },
            {
                imgUrl:require('@/assets/img/awesomes.png'),
                itemName:'awesomes',
                linkWrap:[
                    {
                        linkUrl:'https://www.awesomes.cn/',
                        linkType:'中'
                    }
                ]
            },
            {
                imgUrl:require('@/assets/img/segmentfault.png'),
                itemName:'segmentfault',
                linkWrap:[
                    {
                        linkUrl:'https://segmentfault.com/',
                        linkType:'中'
                    }
                ]
            },
            {
                imgUrl:require('@/assets/img/cnodejs.png'),
                itemName:'cnodejs',
                linkWrap:[
                    {
                        linkUrl:'https://cnodejs.org/',
                        linkType:'中'
                    }
                ]
            },
            {
                imgUrl:require('@/assets/img/w3cplus.png'),
                itemName:'w3cplus',
                linkWrap:[
                    {
                        linkUrl:'http://www.w3cplus.com/',
                        linkType:'中'
                    }
                ]
            },
            {
                imgUrl:require('@/assets/img/w3cschool.png'),
                itemName:'w3cschool',
                linkWrap:[
                    {
                        linkUrl:'https://www.w3cschool.cn/',
                        linkType:'中'
                    },
                    {   
                        linkUrl:'http://www.w3school.com.cn/',
                        linkType:'中'
                    },
                ]
            },
            {
                imgUrl:require('@/assets/img/w3ctech.png'),
                itemName:'w3ctech',
                linkWrap:[
                    {
                        linkUrl:'https://www.w3ctech.com/',
                        linkType:'中'
                    }
                ]
            },
            {
                imgUrl:require('@/assets/img/daqianduan.png'),
                itemName:'daqianduan',
                linkWrap:[
                    {
                        linkUrl:'http://www.daqianduan.com/',
                        linkType:'中'
                    }
                ]
            },
            {
                imgUrl:require('@/assets/img/cnblogs.png'),
                itemName:'博客园',
                linkWrap:[
                    {
                        linkUrl:'https://www.cnblogs.com/',
                        linkType:'中'
                    }
                ]
            },
            {
                imgUrl:require('@/assets/img/csdn.png'),
                itemName:'csdn',
                linkWrap:[
                    {
                        linkUrl:'http://www.csdn.net/',
                        linkType:'中'
                    }
                ]
            },
            {
                imgUrl:require('@/assets/img/mozilla.png'),
                itemName:'mozilla文档',
                linkWrap:[
                    {
                        linkUrl:'https://developer.mozilla.org/zh-CN/',
                        linkType:'英'
                    }
                ]
            },
            {
                imgUrl:require('@/assets/img/qdfuns.png'),
                itemName:'前端网',
                linkWrap:[
                    {
                        linkUrl:'http://www.qdfuns.com/',
                        linkType:'中'
                    }
                ]
            },
            {
                imgUrl:require('@/assets/img/51zxw.png'),
                itemName:'51自学网',
                linkWrap:[
                    {
                        linkUrl:'http://www.51zxw.net/',
                        linkType:'中'
                    }
                ]
            },
            {
                imgUrl:require('@/assets/img/jike.png'),
                itemName:'极客学院',
                linkWrap:[
                    {
                        linkUrl:'http://www.jikexueyuan.com/',
                        linkType:'中'
                    }
                ]
            },
            {
                imgUrl:require('@/assets/img/imooc.png'),
                itemName:'慕课网',
                linkWrap:[
                    {
                        linkUrl:'http://www.imooc.com/',
                        linkType:'中'
                    }
                ]
            }
        ]
    },
    {
        id:'modal-9',
        linkName:'database',
        itemWrap:[
            {
                imgUrl:require('@/assets/img/mogodb.png'),
                itemName:'mogodb',
                linkWrap:[
                    {
                        linkUrl:'http://www.yiibai.com/mongodb/',
                        linkType:'中'
                    },
                    {
                        linkUrl:'http://www.mongoing.com/',
                        linkType:'中'
                    },
                    {   
                        linkUrl:'https://www.mongodb.com/',
                        linkType:'英'
                    }
                ]
            }
        ]
    }
]